// Reporters: human console output, machine JSON, and a Markdown summary for
// GitHub Action PR comments / job summaries.

import pc from "picocolors";
import type { Category, Finding, LintResult, Severity } from "./types.js";

const SEV_ORDER: Severity[] = ["error", "warning", "info"];
const SEV_LABEL: Record<Severity, (s: string) => string> = {
  error: (s) => pc.red(s),
  warning: (s) => pc.yellow(s),
  info: (s) => pc.cyan(s),
};
const SEV_ICON: Record<Severity, string> = { error: "✖", warning: "⚠", info: "ℹ" };

function group(findings: Finding[]): Record<string, Finding[]> {
  const by: Record<string, Finding[]> = {};
  for (const f of findings) {
    const key = f.target ?? f.category;
    (by[key] ??= []).push(f);
  }
  return by;
}

export function renderConsole(res: LintResult): string {
  const lines: string[] = [];
  lines.push("");
  lines.push(pc.bold(`mcp-conform — ${res.toolCount} tool(s) checked`));
  lines.push("");

  if (res.findings.length === 0) {
    lines.push(pc.green("✔ No conformance issues found. Ready to publish."));
  } else {
    const grouped = group(res.findings);
    for (const [where, fs] of Object.entries(grouped)) {
      lines.push(pc.bold(pc.underline(where)));
      const sorted = [...fs].sort(
        (a, b) => SEV_ORDER.indexOf(a.severity) - SEV_ORDER.indexOf(b.severity),
      );
      for (const f of sorted) {
        const sev = SEV_LABEL[f.severity](`${SEV_ICON[f.severity]} ${f.severity}`);
        lines.push(`  ${sev}  ${pc.dim(f.rule)}  ${f.message}`);
        if (f.fix) lines.push(`         ${pc.dim("fix:")} ${f.fix}`);
      }
      lines.push("");
    }
  }

  lines.push(summaryLine(res));
  lines.push(scoreLine(res));
  lines.push("");
  return lines.join("\n");
}

function summaryLine(res: LintResult): string {
  const { error, warning, info } = res.counts;
  return [
    pc.red(`${error} error`),
    pc.yellow(`${warning} warning`),
    pc.cyan(`${info} info`),
  ].join(pc.dim("  ·  "));
}

function scoreLine(res: LintResult): string {
  const color = res.score >= 90 ? pc.green : res.score >= 70 ? pc.yellow : pc.red;
  const verdict = res.pass ? pc.green("PASS") : pc.red("FAIL");
  return pc.bold(`Conformance score: ${color(String(res.score) + "/100")}   ${verdict}`);
}

export function renderJson(res: LintResult): string {
  return JSON.stringify(res, null, 2);
}

export function renderMarkdown(res: LintResult): string {
  const { error, warning, info } = res.counts;
  const verdict = res.pass ? "✅ PASS" : "❌ FAIL";
  const lines: string[] = [];
  lines.push(`## mcp-conform report`);
  lines.push("");
  lines.push(`**Score: ${res.score}/100 — ${verdict}**`);
  lines.push("");
  lines.push(`${res.toolCount} tool(s) checked · ${error} error · ${warning} warning · ${info} info`);
  lines.push("");
  if (res.findings.length === 0) {
    lines.push(`No conformance issues found. Ready to publish. 🎉`);
    return lines.join("\n");
  }
  lines.push(`| Severity | Rule | Where | Issue |`);
  lines.push(`| --- | --- | --- | --- |`);
  const sorted = [...res.findings].sort(
    (a, b) => SEV_ORDER.indexOf(a.severity) - SEV_ORDER.indexOf(b.severity),
  );
  for (const f of sorted) {
    const icon = SEV_ICON[f.severity];
    const where = (f.target ?? f.category).replace(/\|/g, "\\|");
    const msg = f.message.replace(/\|/g, "\\|");
    lines.push(`| ${icon} ${f.severity} | \`${f.rule}\` | \`${where}\` | ${msg} |`);
  }
  lines.push("");
  lines.push(`<sub>Generated by <a href="https://github.com/fernforge/mcp-conform">mcp-conform</a>.</sub>`);
  return lines.join("\n");
}

export const _internal = { group, SEV_ORDER };
export type { Category };
